# Build Stage
FROM node:18-alpine as build

WORKDIR /app

COPY frontend/web-app/package*.json ./
RUN npm install

COPY frontend/web-app/ .
RUN npm run build

# Production Stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
